version: "3.8"

services:
  proctoring-api:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./Code:/app/Code
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
