name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy to Spaces
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          # Configure git to use token
          git config --global credential.helper store
          echo "https://oauth2:$HUGGINGFACE_TOKEN@huggingface.co" > ~/.git-credentials

          # Try to clone the space repository using HTTPS format
          git clone https://huggingface.co/spaces/cuongse/proctoring-system space-repo

          # Copy files to space repository (excluding .git and space-repo)
          rsync -av --exclude='.git' --exclude='space-repo' . space-repo/
          cd space-repo

          # Initialize git and push
          git init
          git add .
          git commit -m "Deploy from GitHub Actions - $(date)"
          git remote add origin https://huggingface.co/spaces/cuongse/proctoring-system 
          git push -u origin main --force
